# docker-compose.yml

version: '3'

services:
  server:
    image: postgrest/postgrest
    ports:
      - "${POSTGREST_HOST_PORT}:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://${DB_CONN_ROLE}:${DB_CONN_PWD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${DB_ANON_ROLE}
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_CONN_ROLE: ${DB_CONN_ROLE}
      DB_CONN_PWD: ${DB_CONN_PWD}
    volumes:
    #  - "./pgdata:/var/lib/postgresql/data"
       - "./initdb:/docker-entrypoint-initdb.d"
     
  swagger:
    image: swaggerapi/swagger-ui
    ports:
        - "${SWAGGER_HOST_PORT}:8080"
    environment:
        API_URL: http://localhost:${POSTGREST_HOST_PORT}/